### ISSUE TITLE
What do you mean by "toy example of Mask R-CNN with two features"?

### ISSUE THREAD

**Issue by WaterKnight1998** [Okery/PyTorch-Simple-MaskRCNN#1]
Is not equivalent to torchvision maskrcnn?

**Comment by Okery** [comment]
No. Compared with torchvision maskrcnn, this model is simplified and intuitive, for its backbone is without FPN and it only supports batch_size =1. It's just a template which is as easy as possible to show the architecture of maskrcnn.
