### ISSUE TITLE
IndexError: list index out of rang

### ISSUE THREAD

**Issue by ts19970816** [Okery/PyTorch-Simple-MaskRCNN#18]

**Comment by bhu1deo** [comment]
List index out of range error during training the model. Specifically in the following function : 

def get_AP(self):
        txt = str(self)
        print(txt)
        values = re.findall(r"(\d{3})\n", txt)
        values = [int(v) / 10 for v in values]
        print(len(values))
        result = {"bbox AP": values[0], "mask AP": values[12]}
        return result

No evaluation results is being reported.

**Comment by NihalHarish** [comment]
I ran into the same issue.

**Comment by Okery** [comment]
Done!
I've fixed the function ```get_AP```.

def get_AP(self):
        txt = str(self)
        values = re.findall(r"(\d{3})\n", txt)
        if len(values) > 0:
            values = [int(v) / 10 for v in values]
            result = {"bbox AP": values[0], "mask AP": values[12]}
            return result
        else:
            return txt
