### ISSUE TITLE
anns = self.dataset['annotations'] KeyError: 'annotations'

### ISSUE THREAD

**Issue by ssablak** [Okery/PyTorch-Simple-MaskRCNN#2]
Hi Okery,
I tried to use your code for training maskrcnn but it gives following error. Do you have any idea about it?
Your help is appreciated.
Thanks,
-Steve

/home/sablakss/anaconda3/envs/flownet/bin/python /home/sablakss/projects/MotionSegmentationNet/train.py --use-cuda --iters 1
cuda: True
available GPU(s): 1
0: {'name': 'GeForce GTX 1060', 'capability': [6, 1], 'total_momory': 5.94, 'sm_count': 10}

device: cuda
loading annotations into memory...
Done (t=12.69s)
creating index...
index created!
loading annotations into memory...
Done (t=0.42s)
creating index...
index created!
Namespace(ckpt_path='./maskrcnn_coco.pth', data_dir='./data/coco2017', dataset='coco', epochs=10, iters=1, lr=0.00125, lr_steps=[22, 26], momentum=0.9, print_freq=100, results='./results.pth', seed=3, use_cuda=True, warmup_iters=117266, weight_decay=0.0001)

already trained: 0 epochs; to 10 epochs

epoch: 1
lr_epoch: 0.0013, factor: 1.0000
0	 0.699	0.160	3.968	0.275	2.662
iter: 540.4, total: 524.6, model: 253.5, backward: 123.9
iter: 201.0, total: 179.0, model: 177.4
all gather: 0.0s
Running per image evaluation...
Evaluate annotation type *bbox*
Traceback (most recent call last):
  File "/home/sablakss/projects/MotionSegmentationNet/train.py", line 118, in <module>
    main(args)
  File "/home/sablakss/projects/MotionSegmentationNet/train.py", line 64, in main
    eval_output, iter_eval = pmr.evaluate(model, d_test, device, args)
  File "/home/sablakss/projects/MotionSegmentationNet/pytorch_mask_rcnn/engine.py", line 68, in evaluate
    coco_evaluator.accumulate(results)
  File "/home/sablakss/projects/MotionSegmentationNet/pytorch_mask_rcnn/datasets/coco_eval.py", line 30, in accumulate
    coco_eval.evaluate() # 15.4s
  File "/home/sablakss/anaconda3/envs/flownet/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 140, in evaluate
    self._prepare()
  File "/home/sablakss/anaconda3/envs/flownet/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 97, in _prepare
    dts=self.cocoDt.loadAnns(self.cocoDt.getAnnIds(imgIds=p.imgIds, catIds=p.catIds))
  File "/home/sablakss/anaconda3/envs/flownet/lib/python3.6/site-packages/pycocotools/coco.py", line 148, in getAnnIds
    anns = self.dataset['annotations']
KeyError: 'annotations'

Process finished with exit code 1

**Comment by ssablak** [comment]
I haven't resolved the issue. The reason could be the version of pycocotools. 
@Okery could you please provide me the pycocotools version. I am currently using pycocotools 2.0.2

**Comment by ssablak** [comment]
@Okery is evaluation module working in your machine? Otherwise, it is not moving to other epocs without evaluation.

**Comment by ssablak** [comment]
I figured out the bug. If the 'results' list is empty in engine.py, it passes the empty list to evaluation which couldn't locate any annotations. I fixed the bug by using the following conditions for evaluation as below

line 69 in engine.py
    if len(results) != 0:
        coco_evaluator.accumulate(results)

    if len(results) > 0:
        coco_evaluator.summarize()

line 70 in train.py
        if len(list(eval_output.buffer)) > 0:
            print(eval_output.get_AP())

**Comment by GLzhan663339** [comment]
Hi Okery,
I tried to use your code for training maskrcnn but it gives following error. Do you have any idea about it?
Your help is appreciated.
Thanks.
--------------
question:
the question  always happens afer training one epoch as follow:
![image](https://user-images.githubusercontent.com/51082354/96946461-03f6cd00-1513-11eb-9552-9892f52bea56.png)
  File "C:\Users\003GPU\.conda\envs\zgl\lib\site-packages\pycocotools\coco.py", line 150, in getAnnIds
    anns = self.dataset['annotations']
KeyError: 'annotations'
---------------
however the  dictionaries has this key('annotations')
I want your help, please. Give me some advice.

**Comment by WWaynee** [comment]
> ## Hi Okery,
> I tried to use your code for training maskrcnn but it gives following error. Do you have any idea about it?
> Your help is appreciated.
> Thanks.
> question:
> the question always happens afer training one epoch as follow:
> ![image](https://user-images.githubusercontent.com/51082354/96947055-a5325300-1514-11eb-8f99-849e09f81763.png)
> 
> ## ![image](https://user-images.githubusercontent.com/51082354/96946461-03f6cd00-1513-11eb-9552-9892f52bea56.png)
> File "C:\Users\003GPU.conda\envs\zgl\lib\site-packages\pycocotools\coco.py", line 150, in getAnnIds
> anns = self.dataset['annotations']
> KeyError: 'annotations'
> however the dictionaries has this key('annotations')
> I want your help, please. Give me some advice.



> ## Hi Okery,
> I tried to use your code for training maskrcnn but it gives following error. Do you have any idea about it?
> Your help is appreciated.
> Thanks.
> question:
> the question always happens afer training one epoch as follow:
> ![image](https://user-images.githubusercontent.com/51082354/96947055-a5325300-1514-11eb-8f99-849e09f81763.png)
> 
> ## ![image](https://user-images.githubusercontent.com/51082354/96946461-03f6cd00-1513-11eb-9552-9892f52bea56.png)
> File "C:\Users\003GPU.conda\envs\zgl\lib\site-packages\pycocotools\coco.py", line 150, in getAnnIds
> anns = self.dataset['annotations']
> KeyError: 'annotations'
> however the dictionaries has this key('annotations')
> I want your help, please. Give me some advice.

Is the problem solved? I have the same problem...
