### ISSUE TITLE
I want to know how to change the classname to my dataset

### ISSUE THREAD

**Issue by lijoe123** [Okery/PyTorch-Simple-MaskRCNN#20]
Hello! Thank you for your work. Would you please tell me how to change the classname to my dataset in coco_dataset? 
Thank you!!!!

**Comment by Okery** [comment]
Hi! I'not sure about your situation. Maybe you can try to change the dataset's attribute ```self.classes``` to your dataset, e.g., ```self.classes = (‘cat', 'dog', 'bird', ...)```.

**Comment by lijoe123** [comment]
Thank you! I'm going to train my own dataset. If i need to fix the code in the  ### **coco_dataset.py** in the highlight like what you say,

class COCODataset(GeneralizedDataset):
    def __init__(self, data_dir, split, train=False):
        super().__init__()
        from pycocotools.coco import COCO
        
        self.data_dir = data_dir
        self.split = split
        self.train = train
        
        ann_file = os.path.join(data_dir, "annotations/instances_{}.json".format(split))
        self.coco = COCO(ann_file)
        self.ids = [str(k) for k in self.coco.imgs]
        
        self._classes = {k: v["name"] for k, v in self.coco.cats.items()}
        **self.classes = tuple(self.coco.cats[k]["name"] for k in sorted(self.coco.cats))**
        # resutls' labels convert to annotation labels
        self.ann_labels = {self.classes.index(v): k for k, v in self._classes.items()}



or write a new###  .py  for my dataset like ### coco_dataset.py  and  ### voc_dataset.py.

By the way, where can i fix the ### num_class
 my dataset is('buildings', 'electrical-tower', 'wire-pole', 'tree', 'person', 'aircraft')

**Comment by lijoe123** [comment]
Thank you! I'm going to train my own dataset. If i need to fix the code in the   **coco_dataset.py** in the highlight like what you say,

class COCODataset(GeneralizedDataset):
    def __init__(self, data_dir, split, train=False):
        super().__init__()
        from pycocotools.coco import COCO
        
        self.data_dir = data_dir
        self.split = split
        self.train = train
        
        ann_file = os.path.join(data_dir, "annotations/instances_{}.json".format(split))
        self.coco = COCO(ann_file)
        self.ids = [str(k) for k in self.coco.imgs]
        
        self._classes = {k: v["name"] for k, v in self.coco.cats.items()}
        **self.classes = tuple(self.coco.cats[k]["name"] for k in sorted(self.coco.cats))**
        # resutls' labels convert to annotation labels
        self.ann_labels = {self.classes.index(v): k for k, v in self._classes.items()}



or write a new###  .py  for my dataset like ### coco_dataset.py  and  ### voc_dataset.py.

By the way, where can i fix the ### num_class
 my dataset is('buildings', 'electrical-tower', 'wire-pole', 'tree', 'person', 'aircraft')

**Comment by lijoe123** [comment]
Thank you! I'm going to train my own dataset. If i need to fix the code in the   **coco_dataset.py** in the highlight like what you say,
 
        self.data_dir = data_dir
        self.split = split
        self.train = train
        
        ann_file = os.path.join(data_dir, "annotations/instances_{}.json".format(split))
        self.coco = COCO(ann_file)
        self.ids = [str(k) for k in self.coco.imgs]
        
        self._classes = {k: v["name"] for k, v in self.coco.cats.items()}
        **self.classes = tuple(self.coco.cats[k]["name"] for k in sorted(self.coco.cats))**
        # resutls' labels convert to annotation labels
        self.ann_labels = {self.classes.index(v): k for k, v in self._classes.items()}



or write a new###  .py  for my dataset like  **coco_dataset.py**  and   **voc_dataset.py**.

By the way, where can i fix the  **num_class**
 my dataset is('buildings', 'electrical-tower', 'wire-pole', 'tree', 'person', 'aircraft')

**Comment by lijoe123** [comment]
我看了一下up主的主页，应该懂中文。就是我想训练自己的数据集，我该在哪修改我自己的**classes** 和 **num_class** 呢？ 是在那个**coco_dataset.py** 里面修改吗？ 还是重新写一个 像**coco_dataset.py** 和 **voc_dataset.py** 的程序?

**Comment by Okery** [comment]
1)如果你的数据集的结构和COCO类似，那你可以直接略微修改coco_dataset.py：
你的数据集可能仅仅是classes与COCO不同，那么你需要修改self._classes，self.classes和self.ann_labels
举个例子：
self._classes = {0: 'buildings, 1: 'electrical-tower', 8: 'wire-pole', 9: 'tree', ...}（这是数据集的classes，其数字id有可能不是连续的，不过这个attribute不是必需的）
self.classes = ('buildings', 'electrical-tower', 'wire-pole', 'tree', ...) （将原来的数据集classes紧凑处理，这样可以减少detector的参数）
self.ann_labels = (0: 0, 1: 1, 2: 8, 3: 9, ...) （将classes与_classes之间做个对应表，为后续计算mAP服务）

2）如果你的数据集结构和COCO差距较大，那么你可以：
自己写一个coco_dataset.py之类的模块
或者将数据集转换成COCO样式的，这点你可以参考voc_dataset.py里的函数

**Comment by lijoe123** [comment]
哇哇哇哇！！！！！！！好感动，太谢谢您了up主。
1、我的数据集是通过**labelme2coco.py** 生成的 annotation 文件，那我应该是只需要修改一下您提到的这几点吧。

2、那这里不需要设置 background 吗？ 还有它的num_class 需要在哪修改？

**Comment by Okery** [comment]
你已经设置self.classes，model会自己读取classes的总数，你不需要设置background和num_class

**Comment by lijoe123** [comment]
好的好的，谢谢您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xin ***@***.***&gt;; 
发送时间: 2021年10月9日(星期六) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Okery/PyTorch-Simple-MaskRCNN] I want to know how to change the classname to my dataset (#20)





 
你已经设置self.classes，model会自己读取classes的总数，你不需要设置background和num_class
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuxiaoxiao666** [comment]
labels = [ann_labels[l] for l in labels]
KeyError: 1

**Comment by liuxiaoxiao666** [comment]
> 你已经设置self.classes，model会自己读取classes的总数，你不需要设置background和num_class

你好 可以参考你的labelme2coco.py吗 我的总是提示KeyError:

**Comment by lijoe123** [comment]
> > 你已经设置self.classes，model会自己读取classes的总数，你不需要设置background和num_class
> 
> 你好 可以参考你的labelme2coco.py吗 我的总是提示KeyError:

n你把你邮箱发我，我给你发

**Comment by liuxiaoxiao666** [comment]
***@***.*** 三克油



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月15日(星期五) 下午4:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Okery/PyTorch-Simple-MaskRCNN] I want to know how to change the classname to my dataset (#20)





   
你已经设置self.classes，model会自己读取classes的总数，你不需要设置background和num_class
  
你好 可以参考你的labelme2coco.py吗 我的总是提示KeyError:
  
n你把你邮箱发我，我给你发
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lijoe123** [comment]
> ***@***.*** 三克油
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年10月15日(星期五) 下午4:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Okery/PyTorch-Simple-MaskRCNN] I want to know how to change the classname to my dataset (#20) 你已经设置self.classes，model会自己读取classes的总数，你不需要设置background和num_class 你好 可以参考你的labelme2coco.py吗 我的总是提示KeyError: n你把你邮箱发我，我给你发 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

看不见，把qq发我，我发你qq邮箱

**Comment by liuxiaoxiao666** [comment]
1406795089

**Comment by liuxiaoxiao666** [comment]
1406795089

**Comment by lijoe123** [comment]
> 1406795089

发了看到了？

**Comment by liuxiaoxiao666** [comment]
看到了 三克油




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月15日(星期五) 下午5:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Okery/PyTorch-Simple-MaskRCNN] I want to know how to change the classname to my dataset (#20)





  
1406795089
  
发了看到了？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JesseYoooo** [comment]
> labels = [ann_labels[l] for l in labels] KeyError: 1

您好，请问这个ann_labels的KeyError问题解决了吗？我遇到了非常相似的情况

**Comment by JesseYoooo** [comment]
> 1)如果你的数据集的结构和COCO类似，那你可以直接略微修改coco_dataset.py： 你的数据集可能仅仅是classes与COCO不同，那么你需要修改self._classes，self.classes和self.ann_labels 举个例子： self._classes = {0: 'buildings, 1: 'electrical-tower', 8: 'wire-pole', 9: 'tree', ...}（这是数据集的classes，其数字id有可能不是连续的，不过这个attribute不是必需的） self.classes = ('buildings', 'electrical-tower', 'wire-pole', 'tree', ...) （将原来的数据集classes紧凑处理，这样可以减少detector的参数） self.ann_labels = (0: 0, 1: 1, 2: 8, 3: 9, ...) （将classes与_classes之间做个对应表，为后续计算mAP服务）
> 
> 2）如果你的数据集结构和COCO差距较大，那么你可以： 自己写一个coco_dataset.py之类的模块 或者将数据集转换成COCO样式的，这点你可以参考voc_dataset.py里的函数

如果是训练coco的一部分，请问这里的classes应该怎么写呢，需要把coco中80个类别全部列出吗？

**Comment by lijoe123** [comment]
我的理解是， 您得把其中的一部分图片挑出来，重新json2coco.py 。我建议您重新开个问题吧，这个博主挺热心的。
