### ISSUE TITLE
当我使用自己的数据集训练时，IoU metric: segm 均为0或者-1 

### ISSUE THREAD

**Issue by wweizhou** [Okery/PyTorch-Simple-MaskRCNN#4]
IoU metric: segm
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 并且一直保持不变，请问是什么原因造成的，我输出coco_result mask是有结果的

**Comment by CoachingJane** [comment]
我和你一样的问题，不过我用的voc2012，请问你voc2012可以跑出结果吗？或者可以加qq交流一下：837036701

**Comment by aitiaowu** [comment]
请问这个问题解决了吗，我也遇到了一样的问题，box是work的，segm和你一样

**Comment by handsomehu0627** [comment]
这个项目和PyTorch上内置的MaskRCNN是一样的，不知道这个repo的作者是不是PyTorch的那个作者。我用torch训练时，box的结果非常好，但是seg的预测结果都是一些非常小的值，比如1e-7（但是非目标区域确实都是0，目标区域值异常小），正常情况下应该是0.x这种数值。这也是为什么你们segm的metric值是0，因为threshold=0的情况下其实segm是没有检测出mask的。

**Comment by handsomehu0627** [comment]
threshold=0.5的情况下
