### ISSUE TITLE
key error: anns = self.dataset['annotations']

### ISSUE THREAD

**Issue by WWaynee** [Okery/PyTorch-Simple-MaskRCNN#8]
How to solve this problem?
I need help.
And how to generate instances_train2017.json file please help me QAQ

**Comment by ssablak** [comment]
I figured out the bug. If the 'results' list is empty in engine.py, it passes the empty list to evaluation which couldn't locate any annotations. I fixed the bug by using the following conditions for evaluation as below

line 69 in engine.py
```
    if len(results) > 0:
        coco_evaluator.accumulate(results)
    if len(results) > 0:
        coco_evaluator.summarize()


```
line 70 in train.py
```
        if len(list(eval_output.buffer)) > 0:
            print(eval_output.get_AP())

```

> How to solve this problem?
> I need help.
> And how to generate instances_train2017.json file please help me QAQ

**Comment by WWaynee** [comment]
> I figured out the bug. If the 'results' list is empty in engine.py, it passes the empty list to evaluation which couldn't locate any annotations. I fixed the bug by using the following conditions for evaluation as below
> 
> line 69 in engine.py
> 
> ```
>     if len(results) > 0:
>         coco_evaluator.accumulate(results)
>     if len(results) > 0:
>         coco_evaluator.summarize()
> ```
> 
> line 70 in train.py
> 
> ```
>         if len(list(eval_output.buffer)) > 0:
>             print(eval_output.get_AP())
> ```
> 
> > How to solve this problem?
> > I need help.
> > And how to generate instances_train2017.json file please help me QAQ

Could you please send me your engine.py? My email: 1242654256@qq.com. Thanks!!!

**Comment by ege114366** [comment]
>    if len(list(eval_output.buffer)) > 0:
>             print(eval_output.get_AP())

Could you please send me your engine.py? My email: ege4366@naver.com. Thanks!!!

**Comment by SYLin117** [comment]
Hi @ssablak, after I replace the code, then I get an `Exception: Please run accumulate() first`, what should I pass to accumulate() if I got no result?

**Comment by Okery** [comment]
The issue of empty results has been solved, in ```coco_eval.py```. You don't need to change ```engine.py```.

**Comment by Okery** [comment]
> How to solve this problem?
> I need help.
> And how to generate instances_train2017.json file please help me QAQ

Well, instances_train2017.json is included in COCO zip file. Maybe you have missed some files while downloading the COCO dataset.

**Comment by Okery** [comment]
```key error: anns = self.dataset['annotations']```
This is probably caused by the missing file ```instances_train2017.json```.
